ollama pull qwen2.5:0.5b
ollama pull llama3.1:latest
ollama pull mistral-openorca:latest
ollama pull glm-4.6:cloud
ollama pull llama2-uncensored:latest
ollama pull gemma3:4b
ollama pull deepseek-r1:latest
ollama pull qwen2.5-coder:latest
ollama pull qwen2.5:latest
ollama pull deepseek-r1:8b
ollama pull llama3.2:latest
ollama pull llava:latest
ollama pull codellama:latest
ollama pull qwen3:4b
ollama pull phi3:mini
ollama pull qwen3:latest
ollama pull llama3:latest
ollama pull ministral-3:latest
ollama pull gpt-oss:latest
ollama pull qwen3-vl:latest
ollama pull gemma:latest
